I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tutorial.rpy", line 568, in script
    python:
  File "game/tutorial.rpy", line 604, in <module>
    for key, values in dic_slave_skills.items():
NameError: name 'dic_slave_skills' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/tutorial.rpy", line 568, in script
    python:
  File "D:\RE\Descargas\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RE\Descargas\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/tutorial.rpy", line 604, in <module>
    for key, values in dic_slave_skills.items():
NameError: name 'dic_slave_skills' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.7.25031702
JONT Port by Rec3ks ver. 0.0.16
Wed May 21 02:41:15 2025
